### ISSUE TITLE
Hey :wave: 

### ISSUE THREAD

**Issue by williamluke4** [alii/nextkit#4]
Hey @alii, I've been testing this out but can seem to find `nextkit/client`
![image](https://user-images.githubusercontent.com/10773719/172561345-5ca3df3f-f770-4e45-b0d2-b6244ccc6a8d.png)

**Comment by alii** [comment]
Ahh sorry just got this notification — I removed nextkit/client as the API was poor and I was yet to find something that worked well. I'll work on it in the future but for now you'll have to write your own fetcher function. Thanks :)
