### ISSUE TITLE
proposal: support different response convention

### ISSUE THREAD

**Issue by jokester** [alii/nextkit#5]
Thanks for the library, it's simple yet extremely convenient.

When using it I found the `SuccessAPIResponse<T>` a little restrictive. (My case is to port existing API endpoints to use this library, so it would be simpler if it's not the only convention).

If we are ok with this, I think I can send a PR afterwards

**Comment by jokester** [comment]
The PR would be like [diff](https://github.com/alii/nextkit/compare/main...jokester:add-bare-res-convention?expand=1) .

**Comment by alii** [comment]
For this you can use `api.raw` — you just need to do `res.json({ custom_response: true });`

Perhaps nextkit does need some proper documentation! 😄 

For example: https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAYygUwIY2QQQAoEk4BmUEIcA5AHbIAeMA1sDGQNwBQrCEFAzvKmMDgBeRCnRY8ACgDerOPLhcAolGJQAXHEkBKYQD442YiGDdkAOhTcIAGwBuyGXF7oArt00BWAAzeANHAgyNzcqADmyJpkyKrQZHAAvtp+rElsrDSQsHAAJsgEqK42fAKWqADuMnIKqNwAnhQIcADiSgAqMlZJcLIKfXBW5gBW1hRV-ROI7jAkAPpWkDyRcDBQrsgpk4nabH0JKWmsQA

**Comment by jokester** [comment]
But `api.raw` would still force use of `ErroredAPIResponse` in error handling. Unless of course the provided http method-specific handler never throws.

**Comment by alii** [comment]
Gotcha, in this respect then what would you rather the behaviour was if the route was to throw? Because basically at this point `nextkit` is really not doing anything, only providing the context variable to routes.

**Comment by jokester** [comment]
I believe that, if we move all code that creates wrapped `SuccessAPIResponse<T> | ErroredAPIResponse` response ( including the catch-then-response part in `getResult` ) into the default `handler`, the `getResult` would be decoupled from certain response convention , and free to use for other possible cases.

Please refer to self-review comment in https://github.com/alii/nextkit/pull/6/files . 

Sorry for the late reply. I just returned from a long weekend.
